//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvicenceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestEntry()
        {
            this.EntryTests = new HashSet<EntryTest>();
        }
    
        public int TestEntryId { get; set; }
        public string PatientName { get; set; }
        public string Picture { get; set; }
        public int Age { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime TestDate { get; set; }
        public System.DateTime DueDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryTest> EntryTests { get; set; }
    }
}
